name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/svg/languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: sususweet, tyq9702@sina.com
      # - uses: lowlighter/metrics@latest
      #   with:
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     filename: assets/svg/recent_activity.svg
      #     base: ""
      #     plugin_activity: yes
      #     plugin_activity_limit: 5
      #     plugin_activity_days: 0
      #     plugin_activity_filter: issue, pr, release, review
      #     plugin_activity_visibility: public
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/svg/notable.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_types: commit, pull_request, issue
          # plugin_notable_skipped: sgoolweb
          plugin_notable_from: all
      # - uses: lowlighter/metrics@latest
      #   with:
      #     filename: assets/svg/followup.user.svg
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     base: ""
      #     plugin_followup: yes
      #     plugin_followup_sections: user
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/svg/base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community
          base_indepth: yes
          commits_authoring: tyq9702@sina.com
          # plugin_isocalendar: yes
          # plugin_isocalendar_duration: full-year
          # plugin_notable: yes
          # plugin_notable_indepth: yes
          # plugin_notable_repositories: yes
          # plugin_notable_types: commit, pull_request, issue
          # plugin_notable_skipped: sgoolweb
          plugin_followup: yes
          plugin_followup_sections: user
          # plugin_activity: yes
          # plugin_activity_limit: 5
          # plugin_activity_days: 0
          # plugin_activity_filter: issue, pr, release, review



